### ISSUE TITLE
No Access-Control-Allow-Origin for Local Swarm Node Usage at File Download

### ISSUE THREAD

**Issue by masterial** [ethereum/web3.js#952]
Download error. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:3000' is therefore not allowed access.

<img width="1272" alt="screen shot 2017-07-26 at 4 38 21 pm" src="https://user-images.githubusercontent.com/11956729/28648191-fb8ca8da-7220-11e7-8164-3d6aa74e11c9.png">

**Comment by MaiaVictor** [comment]
How did you open swarm?

**Comment by destinatis** [comment]
With Mist 0.9.0.

**Comment by avalchev** [comment]
I have the same problem. My project-defaults.yaml is:

```yaml
swarm:
  management:
    security-realms:
      ManagementRealm:
        in-memory-authentication:
          users:
            admin:
              password: 123456
    http-interface-management-interface:
      allowed-origins: http://127.0.0.1:8080
      security-realm: ManagementRealm
```
Password is requested, but in request is resulting into:

```
XMLHttpRequest cannot load http://127.0.0.1:9990/management. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8080' is therefore not allowed access. The response had HTTP status code 403.
```
